### ISSUE TITLE
Bug: No funciona /kits al filtrar el comando

### ISSUE THREAD

**Issue by Pachecon22** [Ajneb97/PlayerKits2#1]
Al poner el comando /kits en la configuración del plugin EasyCommandBlocker y activar la opción command_as_whitelist este detecta como que es un comando invalido y al ejecutar dicho comando con esta opción activada, no funciona.

Me gustaría que se arreglara esto ya que necesito de esa función de ECB para evitar que usen comando como /lp y que vean la versión de LuckPerms.

Este mismo problema lo estoy experimentando también con TabCompleteFilter.
Gracias.

**Comment by Ajneb97** [comment]
Tienes EssentialsX en tu servidor? Si es asi recuerda de desactivar el comando /kit en la configuración de ese plugin.

**Comment by Pachecon22** [comment]
> Tienes EssentialsX en tu servidor? Si es asi recuerda de desactivar el comando /kit en la configuración de ese plugin.

Si tiene EssentialsX, voy a probar lo que me dijiste

**Comment by Ajneb97** [comment]
https://ajneb97.gitbook.io/playerkits-2/common-issues

**Comment by Pachecon22** [comment]
Ok gracias!

**Comment by Pachecon22** [comment]
Hola Ajneb, continuo experimentando el problema, ya he desactivado el comando kit en la configuracion del EssentialsX.
Al usar /kits como usuario normal me sale el mensaje de la 
![Sin título](https://github.com/Ajneb97/PlayerKits2/assets/97350937/c3d4bf62-ff14-4305-8270-964634af5d9b)
captura (mensaje predeterminado de EasyCommandBlocker)

**Comment by Ajneb97** [comment]
Manda tu config del ECB

**Comment by Pachecon22** [comment]
https://pastebin.com/1P3GWRRM

**Comment by Ajneb97** [comment]
La opción use_commands_as_whitelist: true hace que los comandos de las opcion commands, sean los únicos que funcionen dentro de tu server.

**Comment by Pachecon22** [comment]
Lo se, pero yo necesito el tabcomplete y además evitar que los usuarios usen comandos como /lp
Y evitar que vean información de los plugins

**Comment by Pachecon22** [comment]
Osea, debería de quitar esos comandos que salen?

**Comment by Pachecon22** [comment]
Como se podría entonces hacer las 2 cosas, con EasyCommandBlocker y TabCompleteFilter?

**Comment by Ajneb97** [comment]
No puedes bloquear comandos por rango  si eso es a lo que te refieres. Cierro discusión porque el problema es con el EasyCommandBlocker, no con Player Kits 2, puedes seguir preguntandome en la discussion del plugin.
