### ISSUE TITLE
Kit combability issue

### ISSUE THREAD

**Issue by XXX10Tacles** [Ajneb97/PlayerKits2#13]
Hello, anyways i use MMOItems and Shopkeepers plugins and when i put mmoitem in kit, then i grab from /kits command . it does not match original so Shopkeeper does not accept that modified version of items.

How to reproduce a bug.

1. create item in mmoitem.
2. put in kits
3. take mmoitem from kits
4. try to trade using shopkeeper

Keep in mind to put original in shopkeeper, not the one u grabbed from kits.

Looks like kits plugin slightly modify items so, it does not match original.

**Comment by Ajneb97** [comment]
Can you compare the original MMOitems item and the generated PlayerKits item to see what's the difference between them?

**Comment by XXLTentacles** [comment]
From kits

`{AttributeModifiers:[{Amount:0.0d,AttributeName:"minecraft:generic.attack_speed",Name:"mmoitemsDecoy",Operation:0,UUID:[I;-2021319128,-1357757450,-1987131861,-563359508]}],HideFlags:2,MMOITEMS_DYNAMIC_LORE:'["&cAccessory"]',MMOITEMS_ENCHANTS:"[]",MMOITEMS_ITEM_ID:"TEST",MMOITEMS_ITEM_TYPE:"ACCESSORY",MMOITEMS_NAME:"",display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Accessory"}],"text":""}']}}`


Original
`{Amount:0.0d,AttributeName:"minecraft:generic.attack_speed",Name:"mmoitemsDecoy",Operation:0,UUID:[I;-2021319128,-1357757450,-1987131861,-563359508]}],HideFlags:2,MMOITEMS_DYNAMIC_LORE:'["&cAccessory"]',MMOITEMS_ENCHANTS:"[]",MMOITEMS_ITEM_ID:"TEST",MMOITEMS_ITEM_TYPE:"ACCESSORY",MMOITEMS_NAME:"",display:{Lore:['{"extra":[{"italic":false,"color":"red","text":"Accessory"}],"text":""}']}}`

**Comment by XXX10Tacles** [comment]
Bump

**Comment by Ajneb97** [comment]
The original item seems to be missing some attributes on the lore property. Thats the only difference I see.

**Comment by XXX10Tacles** [comment]
> The original item seems to be missing some attributes on the lore property. That's the only difference I see.

yes but problem is that, for shopkeepers it must be 100% identical and as plugin modifies, players are unable to trade.

**Comment by Ajneb97** [comment]
PlayerKits2 saves kits in a way you can fully modify the items in the config, so that's why the item is not 100% exactly (which it should, but as I said, the original item is missing important properties).

What you can do then is to give a command to the player inside the kit, inside of giving them the item. It would be a command provided by MMOItems to give the item directly to the player.

**Comment by XXX10Tacles** [comment]
> PlayerKits2 saves kits in a way you can fully modify the items in the config, so that's why the item is not 100% exactly (which it should, but as I said, the original item is missing important properties).
> 
> What you can do then is to give a command to the player inside the kit, inside of giving them the item. It would be a command provided by MMOItems to give the item directly to the player.

yea writing commands for 100 items it's not fun. :D

**Comment by XXX10Tacles** [comment]
Bug is fixed as update, i quote "-Added new_kit_default_save_mode_original option to the config." fixes current problem. FINALLY. and thank you dev again.
