### ISSUE TITLE
MEMORY LEAK

### ISSUE THREAD

**Issue by Mav124004** [Ajneb97/PlayerKits2#24]
Memory Leak 

![image](https://github.com/user-attachments/assets/0055670a-e6d7-4cc1-96cf-feb3505eb8a6)
![image](https://github.com/user-attachments/assets/b9ba39a5-3895-45fb-8137-f19643376da0)

**Comment by Ajneb97** [comment]
Mmmm why exactly are you telling me this is a memory leak? For a moment I thought the "m" in the graph was PlayerKits 2 and that would be in fact problematic, but it is the "i", which is at 40.7MB, using less memory than other plugins?

The plugin loads data config files into memory, if you don't want that, try using the MySQL configuration.

**Comment by OutDev0** [comment]
I just want to confirm that this was indeed an issue in version 1.16.1. The attached heap dump is from a production server I was working on. I ran the same test using plugin version 1.18.1 (latest), and the issue appears to be resolved.

![Image](https://github.com/user-attachments/assets/6dc07803-6197-4ebc-a862-9500bada88cb)

It doesn’t seem to be a memory leak - rather, it looks like a poor design decision to load all player data at startup.
