### ISSUE TITLE
Duda: Como hacer que se cierre el menú principal con un Item

### ISSUE THREAD

**Issue by Pachecon22** [Ajneb97/PlayerKits2#3]
Muy buenas, me gustaría saber si se puede hacer que el menú que se abre al usar /kits, que haya un item como los demás menús que al darle se cierre.
Ejemplo en la foto:
![image](https://github.com/Ajneb97/PlayerKits2/assets/97350937/8a41a26a-fc17-49d6-9c1d-1aac6f9ce303)

**Comment by Ajneb97** [comment]
Hola. Si se puede, aquí se indica como
https://ajneb97.gitbook.io/playerkits-2/inventory.yml-tutorial#click-commands

**Comment by Pachecon22** [comment]
OK! Muchas gracias.
