### ISSUE TITLE
Duda/Problema: Poner el prefijo de un rango como nombre del kit.

### ISSUE THREAD

**Issue by Pachecon22** [Ajneb97/PlayerKits2#4]
Hola nuevamente, quisiera saber si se puede poner el prefijo de un grupo como nombre de un kit.  Explicación de como necesitaría en las imagenes:
![image](https://github.com/Ajneb97/PlayerKits2/assets/97350937/5ef2bc8e-ecd8-4386-b3ad-5082fc06af8f)
![image](https://github.com/Ajneb97/PlayerKits2/assets/97350937/1f5d7b26-f81c-4430-ba90-17d70eb5682a)

**Comment by Pachecon22** [comment]
@Ajneb97 a lo que me refiero es a poner como nombre del kit un texto con colores rgb (#0000)

**Comment by Ajneb97** [comment]
El formato para colores rgb es #<color>, como #000000
